### ISSUE TITLE
Phoenix edition first draft

### ISSUE THREAD

**Issue by zyphlar** [lifewinning/seeingnetworks#4]
I've begun putting some sketches into Jekyll, but before I got too far I wanted to see if the quality was up to par. I haven't sketched more than a handful, so I'd rather get some honest feedback now than wait until I've invested a bunch more time only to find out it's not quite up to snuff. Thoughts?

https://github.com/lifewinning/seeingnetworks/compare/gh-pages...zyphlar:gh-pages

Screenshot of images with level correction and transparency:

http://imgur.com/a/sfHSK

**Comment by lifewinning** [comment]
AGH. This is what I get for never checking Github notifications. I'm so sorry. 

These are great! I really like the one of the buried cable post. You could probably get away with a little less intense levels, these look pretty high contrast. But yeah, go for it!
